- name: Fabriquer l'APK avec Buildozer
        run: |
          export PATH=$PATH:$HOME/.local/bin
          # On force le nettoyage avant de construire
          buildozer android clean
          buildozer -v android debug
