name: GAIKARO_BUILD
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Installer les dependances
        run: |
          sudo apt update
          sudo apt install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
          # On désinstalle tout Cython existant pour éviter les conflits
          pip3 uninstall -y cython
          # On installe la version exacte qui accepte encore le type 'long'
          pip3 install --user "cython<3.0.0" buildozer virtualenv
      - name: Build
        run: |
          export PATH=$PATH:$HOME/.local/bin
          # Cette commande magique répond 'y' (yes) à chaque fois que le système demande une licence
          yes | buildozer -v android debug

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: GAIKARO-APK
          path: bin/*.apk
